language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
   - python -m unittest test_student
   - python -m unittest test_subject
   - python -m unittest test_diary